// Package lexertest supplies independent per-line expectations for parser
// regression tests and deterministic, multilingual benchmarks.
package lexertest

import "strings"

type Case struct {
	Name      string
	Language  string
	Extension string
	Source    string
	// C = code, M = comment/documentation, B = physically blank.
	Kinds string
}

func Cases() []Case {
	return []Case{
		{Name: "C sharp verbatim doubled quotes", Language: "C#", Extension: "cs",
			Source: "var s = @\"first\\\n\"\" // text\n\"; // real\n// real\n", Kinds: "CCCM"},
		{Name: "C sharp ordinary quote recovers", Language: "C#", Extension: "cs",
			Source: "var s = \"broken\n// real\n", Kinds: "CM"},
		{Name: "F sharp verbatim and nested comments", Language: "F#", Extension: "fs",
			Source: "let x = @\"first\n\"\" (* text *)\n\" // real\n(* outer (* inner *)\nstill outer *)\n", Kinds: "CCCMM"},
		{Name: "SQL doubled quotes and multiline string", Language: "SQL", Extension: "sql",
			Source: "select 'a''-- text\n/* text */'; -- real\n-- real\n", Kinds: "CCM"},
		{Name: "CoffeeScript longest comment opener", Language: "CoffeeScript", Extension: "coffee",
			Source: "# real\n### block\nbody\n### x = 1\nx = '###'\n", Kinds: "MMMCC"},
		{Name: "Lua longest comment opener", Language: "Lua", Extension: "lua",
			Source: "local s = '--[['\n--[[ block\nbody\n]] local x = 1\n-- real\n", Kinds: "CMMCM"},
		{Name: "Clojure semicolon comment", Language: "Clojure", Extension: "clj",
			Source: "; real\n(def x \"; not comment\")\n", Kinds: "MC"},
		{Name: "Julia nested blocks", Language: "Julia", Extension: "jl",
			Source: "#= outer\n#= inner =#\nstill outer\n=# x = 1\n", Kinds: "MMMC"},
		{Name: "Nim nested blocks", Language: "Nim", Extension: "nim",
			Source: "#[ outer\n#[ inner ]#\nstill outer\n]# let x = 1\n", Kinds: "MMMC"},
		{Name: "Swift nested blocks", Language: "Swift", Extension: "swift",
			Source: "/* outer\n/* inner */\nstill outer\n*/ let x = 1\n", Kinds: "MMMC"},
		{Name: "Kotlin longest quote and nested blocks", Language: "Kotlin", Extension: "kt",
			Source: "val s = \"\"\"\n/* text */\n// text\n\"\"\"\n/* outer /* inner */\nstill outer */\n", Kinds: "CCCCMM"},
		{Name: "Bash multiline quotes", Language: "BASH", Extension: "bash",
			Source: "echo '# text'\nvalue='first\n# text\n'\n# real\n", Kinds: "CCCCM"},
		{Name: "Fortran fixed column markers", Language: "FORTRAN Legacy", Extension: "f",
			Source: "ccomment\n      character*x s\n      call f('!')\n!comment\n", Kinds: "MCCM"},
		{Name: "Batch case insensitive word markers", Language: "Batch", Extension: "bat",
			Source: "rem comment\nREMains a variable\n:: comment\n@echo off\n", Kinds: "MCMC"},
		{Name: "Visual Basic doubled quotes", Language: "Visual Basic", Extension: "vb",
			Source: "Dim s = \"it's \"\"quoted\"\"\" ' comment\n' real\n", Kinds: "CM"},
		{Name: "Ruby column anchored blocks", Language: "Ruby", Extension: "rb",
			Source: "puts '=begin'\n=begin\n# docs\n=end\n# real\n", Kinds: "CMMMM"},
		{Name: "Ruby block marker in expression", Language: "Ruby", Extension: "rb",
			Source: "x =beginning\n  =begin\nputs 1\n", Kinds: "CCC"},
		{Name: "Pony documentation versus assigned string", Language: "Pony", Extension: "pony",
			Source: "\"\"\"docs\n// docs\n\"\"\"\nlet s = \"\"\"value\n// text\n\"\"\"\n", Kinds: "MMMCCC"},
		{Name: "Starlark assigned documentation delimiter", Language: "Starlark", Extension: "bzl",
			Source: "def f():\n    '''docs'''\n    x = '''value\n    # text\n    '''\n", Kinds: "CMCCC"},
		{Name: "XML quoted comment marker", Language: "XML", Extension: "xml",
			Source: "<x attr=\"<!--\"/>\n<!-- real\nend --> <y/>\n", Kinds: "CMC"},
		{Name: "Java quoted markers", Language: "Java", Extension: "java",
			Source: "String x = \"/*\"; // text\n// real\nint n;\n", Kinds: "CMC"},
		{Name: "Java text block", Language: "Java", Extension: "java",
			Source: "String x = \"\"\"\n// text\n/* text */\n\n\"\"\"; // real\n// real\n", Kinds: "CCCBCM"},
		{Name: "Java escaped text block closer", Language: "Java", Extension: "java",
			Source: "String x = \"\"\"\n\\\"\"\"\n// text\n\"\"\";\n", Kinds: "CCCC"},
		{Name: "Java unclosed ordinary quote recovers", Language: "Java", Extension: "java",
			Source: "String x = \"broken\n// real\n", Kinds: "CM"},
		{Name: "Java unclosed text block", Language: "Java", Extension: "java",
			Source: "String x = \"\"\"\n/* text\n// text", Kinds: "CCC"},
		{Name: "C++ custom raw delimiter", Language: "C++", Extension: "cpp",
			Source: "auto x = R\"tag(first\n\")\" // text\n/* text */\n)tag\"; /* real\nend */\n", Kinds: "CCCCM"},
		{Name: "C++ empty raw delimiter", Language: "C++", Extension: "cpp",
			Source: "auto x = u8R\"(// text\n/* text */\n)\";\n// real\n", Kinds: "CCCM"},
		{Name: "C++ header raw delimiter", Language: "C++ Header", Extension: "hpp",
			Source: "auto x = LR\"abcdefghijklmnop(\n// text\n)abcdefghijklmnop\";\n", Kinds: "CCC"},
		{Name: "C++ digit separators and characters", Language: "C++", Extension: "cpp",
			Source: "auto n = 1'000; /* real\nend */\nchar c = '\"'; // /*\n", Kinds: "CMC"},
		{Name: "C++ raw prefix inside identifier", Language: "C++", Extension: "cpp",
			Source: "identifierR\"(broken\n// real\n", Kinds: "CM"},
		{Name: "C++ adjacent character token", Language: "C++", Extension: "cpp",
			Source: "char f() { return'a'; } /* real\nend */\n", Kinds: "CM"},
		{Name: "C++ unterminated raw literal", Language: "C++", Extension: "cpp",
			Source: "auto s = R\"tag(\n// text\n/* text", Kinds: "CCC"},
		{Name: "C++ invalid delimiter recovers", Language: "C++", Extension: "cpp",
			Source: "auto s = R\"abcdefghijklmnopq(\n// real\n", Kinds: "CM"},
		{Name: "Rust raw delimiter count", Language: "Rust", Extension: "rs",
			Source: "let x = r###\"first\n\"## // text\n/* text */\n\"###; // real\n// real\n", Kinds: "CCCCM"},
		{Name: "Rust raw byte and C strings", Language: "Rust", Extension: "rs",
			Source: "let a = br\"/*\n// text\n\";\nlet b = cr#\"//\"#;\n", Kinds: "CCCC"},
		{Name: "Rust lifetimes and labels", Language: "Rust", Extension: "rs",
			Source: "fn f<'a>(x: &'a str) { /* real\nend */\n'outer: loop { break 'outer; } // /*\n", Kinds: "CMC"},
		{Name: "Rust character escapes", Language: "Rust", Extension: "rs",
			Source: "let x = '\\u{27}'; /* real\nend */\nlet y = '界'; // /*\nlet z = '\\''; /* real */\n", Kinds: "CMCC"},
		{Name: "Rust nested blocks", Language: "Rust", Extension: "rs",
			Source: "/* outer\n/* inner */\nstill outer\n*/ let n = 1;\n//! docs\n", Kinds: "MMMCM"},
		{Name: "Rust multiline escaped string", Language: "Rust", Extension: "rs",
			Source: "let s = \"first\n// text\n/* text */\n\";\n", Kinds: "CCCC"},
		{Name: "Rust unterminated raw string", Language: "Rust", Extension: "rs",
			Source: "let s = r####\"first\n// text\n\"###", Kinds: "CCC"},
		{Name: "Rust maximum raw delimiter", Language: "Rust", Extension: "rs",
			Source: "let s = r" + strings.Repeat("#", 255) + "\"text\n// text\n\"" +
				strings.Repeat("#", 255) + ";\n// real\n", Kinds: "CCCM"},
		{Name: "Rust unterminated nested block", Language: "Rust", Extension: "rs",
			Source: "/* outer /* inner */\nstill outer", Kinds: "MM"},
		{Name: "Python assigned triple quote", Language: "Python", Extension: "py",
			Source: "value = \"\"\"first\n# text\n\nlast\"\"\"\n# real\n", Kinds: "CCBCM"},
		{Name: "Python module documentation", Language: "Python", Extension: "py",
			Source: "#!/usr/bin/env python\n# preamble\n\"\"\"module\n# docs\n\nend\"\"\"\nx = 1\n", Kinds: "CMMMBMC"},
		{Name: "Python function documentation", Language: "Python", Extension: "py",
			Source: "def f():\n    # preamble\n    r'''docs\n    # docs\n    end'''\n    return '# code'\n", Kinds: "CMMMMC"},
		{Name: "Python nested class documentation", Language: "Python", Extension: "py",
			Source: "class C:\n    \"\"\"class docs\"\"\"\n    def f(self):\n        \"method docs\"\n        return 1\nx = '''value\n# text\n'''\n", Kinds: "CMCMCCCC"},
		{Name: "Python later expression is code", Language: "Python", Extension: "py",
			Source: "x = 1\n\"\"\"expression\n# text\nend\"\"\"\n", Kinds: "CCCC"},
		{Name: "Python formatted and byte strings are code", Language: "Python", Extension: "py",
			Source: "b'''bytes\n# text\n'''\nf'''formatted\n# text\n'''\n", Kinds: "CCCCCC"},
		{Name: "Python non-documentation suite", Language: "Python", Extension: "py",
			Source: "if True:\n    '''expression\n    # text\n    '''\n", Kinds: "CCCC"},
		{Name: "Python adjacent documentation strings", Language: "Python", Extension: "py",
			Source: "'''docs''' 'more docs'\nx = 1\n", Kinds: "MC"},
		{Name: "Python inline suite ends header", Language: "Python", Extension: "py",
			Source: "def f(): return 1\nif True:\n    '''expression'''\n", Kinds: "CCC"},
		{Name: "Python multiline declaration documentation", Language: "Python", Extension: "py",
			Source: "async def f(\n    value: str,\n):\n    '''docs'''\n    return value\n", Kinds: "CCCMC"},
		{Name: "Python escaped newline", Language: "Python", Extension: "py",
			Source: "x = 'start\\\n# text'\n# real\n", Kinds: "CCM"},
		{Name: "Python unterminated ordinary string recovers", Language: "Python", Extension: "py",
			Source: "x = 'broken\n# real\n", Kinds: "CM"},
		{Name: "Python unterminated documentation", Language: "Python", Extension: "py",
			Source: "'''docs\n# docs\nlast", Kinds: "MMM"},
		{Name: "Python unterminated assigned string", Language: "Python", Extension: "py",
			Source: "x = '''value\n# text\nlast", Kinds: "CCC"},
		{Name: "JavaScript template and regex", Language: "JavaScript", Extension: "js",
			Source: "const x = `text\n// text\n${1 /* real */ + 2}`;\nconst r = /[/*]/;\n// real\n", Kinds: "CCCCM"},
		{Name: "Go raw string", Language: "Go", Extension: "go",
			Source: "package p\nvar s = `text\n// text\n`\n// real\n", Kinds: "CCCCM"},
		{Name: "C++ BOM CRLF", Language: "C++", Extension: "cpp",
			Source: "\xef\xbb\xbfauto s = R\"(\r\n// text\r\n)\";\r\n\r\n// real", Kinds: "CCCBM"},
		{Name: "Java long line", Language: "Java", Extension: "java",
			Source: "String s = \"/*" + strings.Repeat("x", 128*1024) + "\";\n// real\n", Kinds: "CM"},
	}
}

// These blocks can repeat without changing their expected classification.
// Fixed sources and names make benchmark fingerprints independent of the host.
func BenchmarkCases() []Case {
	return []Case{
		{Name: "csharp", Language: "C#", Extension: "cs",
			Source: "var s = @\"text\n// literal\n\";\nvar n = 1; // comment\n/* real\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "sql", Language: "SQL", Extension: "sql",
			Source: "select 'text\n-- literal\n';\nselect 1; -- comment\n/* real\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "lua", Language: "Lua", Extension: "lua",
			Source: "local s = '--[['\nlocal n = 1 -- comment\n--[[ real\nend ]]\n\n", Kinds: "CCMMB"},
		{Name: "swift", Language: "Swift", Extension: "swift",
			Source: "let s = \"/*\"\nlet n = 1 // comment\n/* outer /* inner */\nend */\n\n", Kinds: "CCMMB"},
		{Name: "shell", Language: "BASH", Extension: "bash",
			Source: "value='text\n# literal\n'\necho 1 # comment\n# real\n\n", Kinds: "CCCCMB"},
		{Name: "xml", Language: "XML", Extension: "xml",
			Source: "<x attr=\"<!--\"/>\n<!-- real\nend -->\n<y/>\n\n", Kinds: "CMMCB"},
		{Name: "go", Language: "Go", Extension: "go",
			Source: "var s = `text\n// literal\n`\nvar n = 1 // comment\n/* real\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "javascript", Language: "JavaScript", Extension: "js",
			Source: "const r = /[/*]/;\nconst s = `text\n// literal\n${1 /* real */ + 2}`;\n/* real\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "cpp", Language: "C++", Extension: "cpp",
			Source: "auto s = R\"tag(text\n// literal\n)tag\";\nauto n = 1'000; // comment\n/* real\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "java", Language: "Java", Extension: "java",
			Source: "String s = \"\"\"\n// literal\n\"\"\";\nint n = 1; // comment\n/* real\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "rust", Language: "Rust", Extension: "rs",
			Source: "let s = r###\"text\n// literal\n\"###;\nlet n = 1; // comment\n/* outer /* inner */\nend */\n\n", Kinds: "CCCCMMB"},
		{Name: "python", Language: "Python", Extension: "py",
			Source: "def f():\n    '''docs\n    end'''\n    s = '''text\n    # literal\n    end'''\n    return s\n\n", Kinds: "CMMCCCCB"},
	}
}
